spring.application.name=rewardsApp

server.port=8088

aes.secret.key=MySuperSecretAESKey1234567890123
aes.algorithm=AES

spring.datasource.url=jdbc:mysql://localhost:3306/rewards_db
spring.datasource.username=root
spring.datasource.password=Root123$

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.error.include-stacktrace=always

//spring.jpa.hibernate.ddl-auto=update -- not best practise for production
